Add autoClose flag
Briggybros/styled-window-portal pull request #3
Opened 2019-07-07 12:25 UTC by povesteam

<img src="https://user-images.githubusercontent.com/506532/60768202-f07be480-a0ca-11e9-90ca-2d413f83c7de.png">

Add the `autoClose` prop to `<StyledWindowPortal />` component to close child window automatically when parent is closed (via window close, tab close, or refresh).

2019-07-09 08:44 UTC, Briggybros requested changes
See inline comment

2019-07-09 08:44 UTC, Briggybros commented on src/StyledWindowPortal.tsx
> +    }
Is there a case here where if the component is mounted with autoClose = true and is subsequently changed to false before unmounting then this removeEventListener is not called?

Removing the conditional here would mean the event listener is removed if it exists and does not harm if it does not.

2019-07-09 15:26 UTC, povesteam commented
@Briggybros Thanks for the good review!

Updated the code to add and remove the event listener according to the `autoClose` prop, to prevent overloading the document with unnecessary listeners.

![image](https://user-images.githubusercontent.com/506532/60901296-5f497100-a276-11e9-9f59-82cf5d022d58.png)

Also, added a checkbox in the test file, to inspect the listener add/remove process.

![image](https://user-images.githubusercontent.com/506532/60901462-af283800-a276-11e9-9821-9f2df6699519.png)

2019-07-09 15:40 UTC, Briggybros approved these changes

2019-07-09 15:40 UTC, merged

2019-07-09 15:41 UTC, Briggybros commented
@povesteam Thank you for the feature :)

2019-07-10 05:56 UTC, povesteam commented
Glad to improve something I'm using.

Thank you for the package!